version: "3.5"

services:
  friendly.kafka.1:
    image: acntechie/kafka
    container_name: friendly.kafka.1
    ports:
      - "9091:9091"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_PORT=9091
      - ZOOKEEPER_HOSTS=friendly.zookeeper.1:2181,friendly.zookeeper.2:2181,friendly.zookeeper.3:2181
    depends_on:
      - friendly.zookeeper.1
      - friendly.zookeeper.2
      - friendly.zookeeper.3
    networks:
    - kafka

  friendly.kafka.2:
    image: acntechie/kafka
    container_name: friendly.kafka.2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_PORT=9092
      - ZOOKEEPER_HOSTS=friendly.zookeeper.1:2181,friendly.zookeeper.2:2181,friendly.zookeeper.3:2181
    depends_on:
      - friendly.zookeeper.1
      - friendly.zookeeper.2
      - friendly.zookeeper.3
    networks:
    - kafka

  friendly.kafka.3:
    image: acntechie/kafka
    container_name: friendly.kafka.3
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_PORT=9093
      - ZOOKEEPER_HOSTS=friendly.zookeeper.1:2181,friendly.zookeeper.2:2181,friendly.zookeeper.3:2181
    depends_on:
      - friendly.zookeeper.1
      - friendly.zookeeper.2
      - friendly.zookeeper.3
    networks:
    - kafka

  friendly.zookeeper.1:
    image: acntechie/zookeeper
    container_name: friendly.zookeeper.1
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=friendly.zookeeper.1:2888:3888,friendly.zookeeper.2:2888:3888,friendly.zookeeper.3:2888:3888
    networks:
    - kafka

  friendly.zookeeper.2:
    image: acntechie/zookeeper
    container_name: friendly.zookeeper.2
    environment:
      - ZOOKEEPER_ID=2
      - ZOOKEEPER_HOSTS=friendly.zookeeper.1:2888:3888,friendly.zookeeper.2:2888:3888,friendly.zookeeper.3:2888:3888
    networks:
    - kafka

  friendly.zookeeper.3:
    image: acntechie/zookeeper
    container_name: friendly.zookeeper.3
    environment:
      - ZOOKEEPER_ID=3
      - ZOOKEEPER_HOSTS=friendly.zookeeper.1:2888:3888,friendly.zookeeper.2:2888:3888,friendly.zookeeper.3:2888:3888
    networks:
    - kafka

networks:
  kafka:
    name: kafka
