version: "2"

services:
  friendly_kafka_1:
    image: acntechie/kafka
    container_name: friendly_kafka_1
    ports:
      - "9091:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER_HOSTS=friendly_zookeeper_1:2181,friendly_zookeeper_2:2181,friendly_zookeeper_3:2181
    depends_on:
      - friendly_zookeeper_1
      - friendly_zookeeper_2
      - friendly_zookeeper_3
    networks:
    - zookeeper

  friendly_kafka_2:
    image: acntechie/kafka
    container_name: friendly_kafka_2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=2
      - ZOOKEEPER_HOSTS=friendly_zookeeper_1:2181,friendly_zookeeper_2:2181,friendly_zookeeper_3:2181
    depends_on:
      - friendly_zookeeper_1
      - friendly_zookeeper_2
      - friendly_zookeeper_3
    networks:
    - zookeeper

  friendly_kafka_3:
    image: acntechie/kafka
    container_name: friendly_kafka_3
    ports:
      - "9093:9092"
    environment:
      - KAFKA_BROKER_ID=3
      - ZOOKEEPER_HOSTS=friendly_zookeeper_1:2181,friendly_zookeeper_2:2181,friendly_zookeeper_3:2181
    depends_on:
      - friendly_zookeeper_1
      - friendly_zookeeper_2
      - friendly_zookeeper_3
    networks:
    - zookeeper

  friendly_zookeeper_1:
    image: acntechie/zookeeper
    container_name: friendly_zookeeper_1
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=friendly_zookeeper_1:2888:3888,friendly_zookeeper_2:2888:3888,friendly_zookeeper_3:2888:3888
    networks:
    - zookeeper

  friendly_zookeeper_2:
    image: acntechie/zookeeper
    container_name: friendly_zookeeper_2
    environment:
      - ZOOKEEPER_ID=2
      - ZOOKEEPER_HOSTS=friendly_zookeeper_1:2888:3888,friendly_zookeeper_2:2888:3888,friendly_zookeeper_3:2888:3888
    networks:
    - zookeeper

  friendly_zookeeper_3:
    image: acntechie/zookeeper
    container_name: friendly_zookeeper_3
    environment:
      - ZOOKEEPER_ID=3
      - ZOOKEEPER_HOSTS=friendly_zookeeper_1:2888:3888,friendly_zookeeper_2:2888:3888,friendly_zookeeper_3:2888:3888
    networks:
    - zookeeper

networks:
  zookeeper:
