version: "3.5"

services:
  lonely.kafka:
    image: acntechie/kafka
    container_name: lonely.kafka
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_HOSTS=lonely.zookeeper:2181
    depends_on:
      - lonely.zookeeper
    networks:
    - kafka

  lonely.zookeeper:
    image: acntechie/zookeeper
    container_name: lonely.zookeeper
    networks:
    - kafka

networks:
  kafka:
    name: kafka
